### ISSUE TITLE
Реализовать веб-сервис создания транзакций

### ISSUE THREAD

**Issue by amivanoff** [agentlab/rdf-scheme-editor-server#17]
Портировать класс org.eclipse.rdf4j.http.server.repository.transaction.TransactionStartController

Документация по REST API https://rdf4j.eclipse.org/documentation/rest-api/#starting-transactions

**Comment by amivanoff** [comment]
https://github.com/eclipse/rdf4j/blob/master/tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java

**Comment by AleksZaporozhets** [comment]
Исправил комиты, не пойму с API, так как по документации написано, что там же нужна не полная ссылка, добавил файл Transaction
