### ISSUE TITLE
Реализовать метод добавления statements в неявно заданный граф RDF репозитория POST запросом

### ISSUE THREAD

**Issue by amivanoff** [agentlab/rdf-scheme-editor-server#31]
org.eclipse.rdf4j.http.server.repository.graph.GraphController

https://rdf4j.eclipse.org/documentation/rest-api/#add-statements-to-a-directly-referenced-named-graph-in-the-mem-rdf-repository

**Comment by amivanoff** [comment]
Задание упрощаем, сегодня отпишу

**Comment by smurfshma** [comment]
1. исходное состояние графа (уже есть стейтментс). Получаем по гет запросу (уже был реализован)
![1](https://user-images.githubusercontent.com/51400965/65359259-ac49ac00-dc04-11e9-801d-04598e68ef00.png)
2. посылаем стейтменты в теле (миша и иванов). в ответ 200 ОК
`@base <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rel: <http://www.perceive.net/schemas/relationship/> .

<#misha>
    rel:enemyOf <#swd> ;
    a foaf:Person ;
    foaf:name "Шевченко" .
    
<#ivanov>
    rel:enemyOf <#illiteracy> ;
    a foaf:Person ;
    foaf:name "Superman", "Алексей Михайлович"@ru .
`
![2](https://user-images.githubusercontent.com/51400965/65359284-bc618b80-dc04-11e9-948c-ac4db242bd78.png)
3. проверяем, обновились ли стеймтенты. И да, все, что добавляли — добавлено.
![3](https://user-images.githubusercontent.com/51400965/65359303-ca171100-dc04-11e9-9e7c-d462245b9f87.png)
